# Generated by Django 4.2.5 on 2023-10-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_rename_viewer_lesson_viewed_alter_product_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='viewed',
        ),
        migrations.AlterField(
            model_name='product',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='viewed',
            field=models.ManyToManyField(null=True, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
