# Generated by Django 4.2.5 on 2023-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_products_access_delete_products_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_access',
            name='products',
            field=models.ManyToManyField(null=True, related_name='allowed_products', to='main.product'),
        ),
    ]
